default_config:
logger:
  default: error
  logs:
    custom_components.datetime_sensors: debug

input_datetime:
  test1:
    name: Input datetime test 1
    has_date: False
    has_time: true

binary_sensor:
  - platform: datetime_sensors
    datetime_input: input_datetime.test1
    name: test1_triggered
  - platform: datetime_sensors
    datetime_input: input_datetime.test2